// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return wrapSupabaseClient(client);
}

function wrapSupabaseClient(client: any) {
  const originalFrom = client.from.bind(client);

  client.from = (table: string) => {
    const queryBuilder = originalFrom(table);

    const originalDelete = queryBuilder.delete.bind(queryBuilder);
    const originalUpdate = queryBuilder.update.bind(queryBuilder);

    queryBuilder.delete = (options?: any) => {
      const filterBuilder = originalDelete(options);
      return createSafeFilterBuilder(filterBuilder, table, "DELETE");
    };

    queryBuilder.update = (values: any, options?: any) => {
      const filterBuilder = originalUpdate(values, options);
      return createSafeFilterBuilder(filterBuilder, table, "UPDATE");
    };

    return queryBuilder;
  };

  return client;
}

function createSafeFilterBuilder(filterBuilder: any, table: string, operation: string, state = { hasValidFilter: false }) {
  return new Proxy(filterBuilder, {
    get(target, prop, receiver) {
      const val = Reflect.get(target, prop, receiver);

      if (typeof val === "function") {
        return function (...args: any[]) {
          const filterMethods = [
            "eq", "neq", "gt", "gte", "lt", "lte", "like", "ilike", "is", "in", 
            "contains", "containedBy", "rangeGt", "rangeGte", "rangeLt", "rangeLte", 
            "rangeAdjacent", "overlaps", "textSearch", "match", "filter", "or", "and", "not"
          ];

          if (filterMethods.includes(prop as string)) {
            const [column, value] = args;
            if (value === undefined || value === null || value === "" || value === "undefined") {
              const errorMsg = `[Supabase Safe Guard] Blocked ${operation} on table '${table}': filter for column '${column}' has an invalid value (${value}).`;
              console.error(errorMsg);
              throw new Error(errorMsg);
            }
            state.hasValidFilter = true;
          }

          if (prop === "then") {
            if (!state.hasValidFilter) {
              const errorMsg = `[Supabase Safe Guard] Blocked unfiltered ${operation} on table '${table}' to prevent accidental mass deletion/updates.`;
              console.error(errorMsg);
              throw new Error(errorMsg);
            }
          }

          const result = val.apply(target, args);
          if (result && typeof result === "object" && typeof result.then === "function") {
            return createSafeFilterBuilder(result, table, operation, state);
          }
          return result;
        };
      }

      return val;
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
